config/routes.rb
Rails.application.routes.draw do

      root 'index#home'
      get 'about', to: 'index#about'
      get 'new', to: 'articles#new'
      get 'all', to: 'articles#all'
      resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    def new
        @article = Article.new
    end
    def edit
        @article = Article.find(params[:id])
    end
    def create
       @article = Article.new(article_params)
       #@article.save
       #redirect_to articles_path(@article)
       if @article.save
           flash[:notice] = "Article was successfully created"
          redirect_to article_path(@article) 
       else
           render 'new'
       end
    end
    
    def update
            @article = Article.find(params[:id])
            if @article.update(article_params)
                flash[:notice] = "Article was successfully updated"
                redirect_to article_path(@article)
            else
                render 'edit'
            end
    end
    def show
       @article = Article.find(params[:id]) 
    end
    private
        def article_params
            params.require(:article).permit(:title, :description)
        end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
    def home
        
    end
    def about
        
    end
    def all
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Untitled Document</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://use.typekit.net/ojx8uof.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
    <style>
        body {
            margin:0;
            padding: 0;
        }
        body a {
            text-decoration: none;
            color: white;
        }
        .Container {
            width: 100%;
            height: auto;
            overflow: auto;
            overflow-x: hidden;
            padding: 0; margin: 0;
            background: rgba(0,0,0,0.00);
            padding: 0px 0px 0px 0px;
        }
        header {
            margin: 0; 
            width: 100%;
            height: auto;
            margin: 0 auto;
            background: rgba(0, 0, 0, 0.7);
            overflow: auto;
            border-bottom: rgba(247, 115, 0, 1.0) 2px solid;
            margin-bottom: 0px;
            border-radius: 0px;
        }
        footer {
            margin: 0; margin-top: 20px;
            width: 100%;
            height: 20px;
            background: rgba(0, 106, 164, .0);
            border-bottom: rgba(247, 115, 0, 0.0) 2px solid;
            text-align: center;
            border-top: rgba(0,0,0,0.10) thin solid;;
            padding: 20px 50px;
            font-family: sans-serif; color: white;
            font-weight: 100;
            margin: 0 auto;
            margin-top: 50px;
            color: black;
            float: left;
        }
        footer small {
            float: left;
        }
        header ul {
            margin: 0;
            height: auto;
            overflow: auto;
            float: left;
            padding: 0px 0 0 0;
        }
        .Fixedwidth ul li {
            list-style: none;
            float: left;
            margin-left: 10px;
            padding: 16px 10px 0  10px;
            font-size: 16px;
            font-family: sans-serif;
            font-weight: 300;
            color: white;
        }
        header ul li strong {
            font-size: 10px;
            color: white;
        }
        .Active {
            color: rgba(247, 115, 0, 1.0);
            text-shadow: 1px 2px 5px 2px;
        }
        #Ac {
            cursor: pointer;
        }
        .AcHover {
            background: rgba(255,255,255,0.10);
            height: 35px;
        }
        #SubMenu {
            margin: 0;
            position: absolute;
            top: 53px;
            margin-left: -10px;
            height: auto;
            cursor: pointer;
            overflow: auto;
            width: 180px;
            float: left;
            padding: 0;
            background: rgba(0,0,0, 0.80);
            border-radius: 0px 0px 10px 10px;
            box-sizing: border-box;
            padding: 0px 10px 0px 0px;
            display: none;
            z-index: +999;
            border-bottom: rgba(247, 115, 0, 1.0) 2px solid;
            border-left: rgba(247, 115, 0, 1.0) 0px solid;
            color: black;
        }
        #signIn {
            float: right;
        }
        #SubMenu li {
            list-style: none;
            float: none;
            display: inline-table;
            width: 80%;
            margin-left: 10px;
            padding: 10px 10px;
            font-size: 16px;
            font-family: sans-serif;
            font-weight: 300;
            color: white;
        }
        .Fixedwidth {
            width: 100%;
            height: auto;
            overflow: auto;
            margin: 0 auto;
            background: rgba(0,0,0, 0.0);
            padding: 0 0 0 0;
        }
        .Fixedwidth input {
            width: 150px;
            height: 31px;
        }
        #search {
            margin-left: 10px;
            margin-top: 10px; margin-bottom: 10px;
            border: none;
            padding: 10px;
            box-sizing: border-box;
            border-radius:2px;
            box-shadow: inset rgba(0,0,0, 0.20) 1px 1px 5px 1px;
        }
        #submit {
            width: 80px;
            height: 31px;
            margin-left: 5px;
            border: none;
            padding: none;
            background: white;
            border-radius:2px;
        }
        .Content {
            width: 100%;
            height: auto;
            overflow: auto;
            text-align: center;
            float: left;
            z-index: -1;
            background: rgba(0,0,0,0.00);
            
        } 
        .Fixedwidthcontent {
            width: 100%;
            height: auto;
            overflow: auto;
            margin:  0 auto;
            background: rgba(255,255,255, 0.0);
            padding: 10px 20px;
            box-sizing: border-box;
            background-size: cover;
            background-position: 0px -100px;
            opacity: .3;
            z-index: -1;
            position: absolute;
            top: 56px;
            
        }  
        header h2 {
            width: 200px;
            font-family: sans-serif;
            float: left;
            margin: 0;
            color: aliceblue;
            font-weight: 400;
            padding-top: 10px;
            margin-left: 20px;
        }
        .cta-Container {
            width: 90%;
            height: auto;
            overflow: auto;
            background:rgba(0,0,0,0.05);
            border-radius: 20px;
            z-index: +999;
            margin: 0 auto;
            margin-top: 50px;
            font-family: sans-serif;
            color: black;
            padding-bottom: 50px;
        }
        .cta-Container label {
            width: 100%;
            font-size: 22px;
            float: left;
            margin-bottom: 10px;
            margin-top: 10px;
        }
        
        .cta-Container  h1, label, h3 {
            color: rgba(0,0,0, 0.60);
        }
        .cta-Container input {
            float: left;
            width: 60%;
            margin-left: 20%;
            height: 30px;
            font-size: 14px;
            box-sizing: border-box;
            padding: 5px 10px;
        }
        .cta-Container textarea {
            width: 80%;
            height: 200px;
            margin-left: 10%;
            float: left;
            font-weight: 100;
            font-size: 14px;
            box-sizing: border-box;
            padding: 5px 10px;
        }
        #JoinNow {
            width: 15%;
            height: 35px;
            border: none;
            padding: none;
            background: rgba(0,0,0,0.05);
            float: left;
            border-radius:2px;
            font-size: 1em;
            margin-left: 42.5%;
            margin-top:20px;
            margin-bottom: 20px;
        }
        .Title {
            width: 100%;
            height: auto;
        }
        .Description {
            width: 100%;
            height: auto;
        }
        .Articles-container {
            width: 80%;
            height: auto;
            overflow: auto;
            background: rgba(255,255,255,0.70);
            margin: 0 auto; 
            margin-top: 20px;
            border-radius: 10px 0px 10px 0px;
            border-bottom: rgba(247, 115, 0, 1.0) 2px solid;
            border-top: rgba(247, 115, 0, 1.0) 2px solid;
        }
        .Articles-container a {
            color:black;
        }
        .cta-Container a {
            color:black;
        }
    </style>
    <script>
     $(document).ready(function(){
         $('#Ac').click(function(){
            $('#Ac').toggleClass('AcHover')
            $('#SubMenu').slideToggle(400); 
         });
         $('.Content').click(function(){
            $('#Ac').toggleClass('AcHover')
            $('#SubMenu').slideUp(400); 
         });
     });
    </script>
<body>
<div class="Container">
    <header>
    <div class="Fixedwidth"> 
        <h2><%= link_to 'The Alpha Blog', root_path %></h2>
        <ul> 
            <li>Articles</li>
            <li>Link</li>
            <li class="Active" id="Ac">Actions <strong>&#x25BC;</strong>
                <ul id="SubMenu">
                    <li><%= link_to 'New Article', new_path %></li>
                    <li><%= link_to 'Popular Articles', all_path %></li>
                    <li>Newsletters</li>
                    <hr>
                    <li>Separated Link</li>
                    <hr>
                    <li>Another Link</li>
                </ul>
            </li>
        </ul>
        <ul id="signIn">
            <li>Sign In</li>
            <li>Sign Up</li>
        </ul>
        <input type="text" placeholder="Search" name="search" id="search">
        <button type="submit" value="Submit" id="submit">Submit</button>
    </div>
    </header>
    <div class="Content"> 
        <div class="cta-Container">
            <h1>The Alpha Blog</h1>
            <h3>Article Collection</h3>
            
            <%= link_to 'Create New Article', new_article_path %>
            <%= @articles.each do |article| %>
            <div class="Articles-container"> 
                 <div class="Title"><p><%= article.title %></p></div>
                 <div class="Description"> <p><%= article.description %> </p></div>
                 <%= link_to 'Edit', edit_article_path(article) %> |
                 <%= link_to 'Show', article_path(article) %>
            </div>
            <% end %>
            
        </div>
        <div class="Fixedwidthcontent"> </div>
        
    </div>
    <footer>
        <small>All rights reserved @Alpha-Block: Display purposes for Jamell Daniels Portfolio</small>
    </footer>
</div>
</body>
</html>

app/views/articles/new.html.erb
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Untitled Document</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://use.typekit.net/ojx8uof.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
    <style>
        body {
            margin:0;
            padding: 0;
        }
        body a {
            color:white;
            text-decoration:none;
        }
        .Container {
            width: 100%;
            height: auto;
            overflow: auto;
            overflow-x: hidden;
            padding: 0; margin: 0;
            background: rgba(0,0,0,0.00);
            padding: 0px 0px 0px 0px;
        }
        header {
            margin: 0; 
            width: 100%;
            height: auto;
            margin: 0 auto;
            background: rgba(0, 0, 0, 0.7);
            overflow: auto;
            border-bottom: rgba(247, 115, 0, 1.0) 2px solid;
            margin-bottom: 0px;
            border-radius: 0px;
        }
        footer {
            margin: 0; margin-top: 20px;
            width: 100%;
            height: 20px;
            background: rgba(0, 106, 164, .0);
            border-bottom: rgba(247, 115, 0, 0.0) 2px solid;
            text-align: center;
            border-top: rgba(0,0,0,0.10) thin solid;;
            padding: 20px 50px;
            font-family: sans-serif; color: white;
            font-weight: 100;
            margin: 0 auto;
            margin-top: 50px;
            color: black;
            float: left;
        }
        footer small {
            float: left;
        }
        header ul {
            margin: 0;
            height: auto;
            overflow: auto;
            float: left;
            padding: 0px 0 0 0;
        }
        .Fixedwidth ul li {
            list-style: none;
            float: left;
            margin-left: 10px;
            padding: 16px 10px 0  10px;
            font-size: 16px;
            font-family: sans-serif;
            font-weight: 300;
            color: white;
        }
        header ul li strong {
            font-size: 10px;
            color: white;
        }
        .Active {
            color: rgba(247, 115, 0, 1.0);
            text-shadow: 1px 2px 5px 2px;
        }
        #Ac {
            cursor: pointer;
            
        }
        #SubMenu {
            margin: 0;
            position: absolute;
            top: 53px;
            margin-left: -10px;
            height: auto;
            cursor: pointer;
            overflow: auto;
            width: 180px;
            float: left;
            padding: 0;
            background: rgba(0,0,0, 0.80);
            border-radius: 0px 0px 10px 10px;
            box-sizing: border-box;
            padding: 0px 10px 0px 0px;
            display: none;
            z-index: +999;
            border-bottom: rgba(247, 115, 0, 1.0) 2px solid;
            border-left: rgba(247, 115, 0, 1.0) 0px solid;
            color: black;
        }
        #SubMenu li {
            list-style: none;
            float: none;
            display: inline-table;
            width: 80%;
            margin-left: 10px;
            padding: 10px 10px;
            font-size: 16px;
            font-family: sans-serif;
            font-weight: 300;
            color: white;
        }
        .Fixedwidth {
            width: 100%;
            height: auto;
            overflow: auto;
            margin: 0 auto;
            background: rgba(0,0,0, 0.0);
            padding: 0 0 0 0;
        }
        .Fixedwidth input {
            width: 150px;
            height: 31px;
        }
        #search {
            margin-left: 10px;
            margin-top: 10px; margin-bottom: 10px;
            border: none;
            padding: 10px;
            box-sizing: border-box;
            border-radius:2px;
            box-shadow: inset rgba(0,0,0, 0.20) 1px 1px 5px 1px;
        }
        #submit {
            width: 80px;
            height: 31px;
            margin-left: 5px;
            border: none;
            padding: none;
            background: white;
            border-radius:2px;
        }
        .Content {
            width: 100%;
            height: auto;
            overflow: auto;
            text-align: center;
            float: left;
            z-index: -1;
            background: rgba(0,0,0,0.00);
            
        } 
        .Fixedwidthcontent {
            width: 100%;
            height: auto;
            overflow: auto;
            margin:  0 auto;
            background: rgba(255,255,255, 0.0);
            padding: 10px 20px;
            box-sizing: border-box;
            background-size: cover;
            background-position: 0px -100px;
            opacity: .3;
            z-index: -1;
            position: absolute;
            top: 56px;
            
        }  
        header h2 {
            width: 200px;
            font-family: sans-serif;
            float: left;
            margin: 0;
            color: aliceblue;
            font-weight: 400;
            padding-top: 10px;
            margin-left: 20px;
        }
        .cta-Container {
            width: 90%;
            height: auto;
            overflow: auto;
            background:rgba(0,0,0,0.05);
            border-radius: 20px;
            z-index: +999;
            margin: 0 auto;
            margin-top: 50px;
            font-family: sans-serif;
            color: black;
        }
        .cta-Container label {
            width: 100%;
            font-size: 22px;
            float: left;
            margin-bottom: 10px;
            margin-top: 10px;
        }
        
        .cta-Container  h1, label, h3 {
            color: rgba(0,0,0, 0.60);
        }
        .cta-Container input {
            float: left;
            width: 60%;
            margin-left: 20%;
            height: 30px;
            font-size: 14px;
            box-sizing: border-box;
            padding: 5px 10px;
        }
        .cta-Container textarea {
            width: 80%;
            height: 200px;
            margin-left: 10%;
            float: left;
            font-weight: 100;
            font-size: 14px;
            box-sizing: border-box;
            padding: 5px 10px;
        }
        input[name="commit"] {
            width: 15%;
            height: 35px;
            border: none;
            padding: none;
            background: rgba(0,0,0,0.05);
            float: left;
            border-radius:2px;
            font-size: 1em;
            margin-left: 42.5%;
            margin-top:20px;
            margin-bottom: 20px;
        }
        #signIn {
            float: right;
        }
        .AcHover {
            background: rgba(255,255,255,0.10);
            height: 35px;
        }
    </style>
    <script>
     $(document).ready(function(){
         $('#Ac').click(function(){
            $('#Ac').toggleClass('AcHover')
            $('#SubMenu').slideToggle(400); 
         });
         $('.Content').click(function(){
            $('#Ac').toggleClass('AcHover')
            $('#SubMenu').slideUp(400); 
         });
     });
    </script>
<body>
<div class="Container">
    <header>
    <div class="Fixedwidth"> 
        <h2><%= link_to 'The Alpha Blog', root_path %></h2>
        <ul> 
            <li>Articles</li>
            <li>Link</li>
            <li class="Active" id="Ac">Actions <strong>&#x25BC;</strong>
                <ul id="SubMenu">
                    <li><%= link_to 'New Article', new_path %></li>
                    <li><%= link_to 'Popular Articles', all_path %></li>
                    <li>Newsletters</li>
                    <hr>
                    <li>Separated Link</li>
                    <hr>
                    <li>Another Link</li>
                </ul>
            </li>
        </ul>
        <ul id="signIn">
            <li>Sign In</li>
            <li>Sign Up</li>
        </ul>
        <input type="text" placeholder="Search" name="search" id="search">
        <button type="submit" value="Submit" id="submit">Submit</button>
    </div>
    </header>
    <div class="Content"> 
        <div class="cta-Container">
            <h1>The Alpha Blog</h1>
            <h3>Create an article</h3>
            <% if @article.errors.any? %>
    <h2>The following errors prevented the article from being created</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_for @article do |f| %>
    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= link_to "Back to article listings", articles_path %>
        </div>
        <div class="Fixedwidthcontent"> </div>
        
    </div>
    <footer>
        <small>All rights reserved @Alpha-Block: Display purposes for Jamell Daniels Portfolio</small>
    </footer>
</div>
</body>
</html>

app/views/articles/show.html.erb
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Untitled Document</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://use.typekit.net/ojx8uof.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
    <style>
        body {
            margin:0;
            padding: 0;
        }
        body a {
            color:white;
            text-decoration:none;
        }
        .Container {
            width: 100%;
            height: auto;
            overflow: auto;
            overflow-x: hidden;
            padding: 0; margin: 0;
            background: rgba(0,0,0,0.00);
            padding: 0px 0px 0px 0px;
        }
        header {
            margin: 0; 
            width: 100%;
            height: auto;
            margin: 0 auto;
            background: rgba(0, 0, 0, 0.7);
            overflow: auto;
            border-bottom: rgba(247, 115, 0, 1.0) 2px solid;
            margin-bottom: 0px;
            border-radius: 0px;
        }
        footer {
            margin: 0; margin-top: 20px;
            width: 100%;
            height: 20px;
            background: rgba(0, 106, 164, .0);
            border-bottom: rgba(247, 115, 0, 0.0) 2px solid;
            text-align: center;
            border-top: rgba(0,0,0,0.10) thin solid;;
            padding: 20px 50px;
            font-family: sans-serif; color: white;
            font-weight: 100;
            margin: 0 auto;
            margin-top: 50px;
            color: black;
            float: left;
        }
        footer small {
            float: left;
        }
        header ul {
            margin: 0;
            height: auto;
            overflow: auto;
            float: left;
            padding: 0;
        }
        ul:first-child {
            display:none;
        }
        .Fixedwidth ul li {
            list-style: none;
            float: left;
            margin-left: 10px;
            padding: 10px 10px;
            font-size: 16px;
            font-family: sans-serif;
            font-weight: 300;
            color: white;
        }
        header ul li strong {
            font-size: 10px;
            color: white;
        }
        .Active {
            color: rgba(247, 115, 0, 1.0);
            text-shadow: 1px 2px 5px 2px;
        }
        #Ac {
            cursor: pointer;
            
        }
        #SubMenu {
            margin: 0;
            position: absolute;
            top: 60px; 
            height: auto;
            cursor: pointer;
            overflow: auto;
            width: 180px;
            float: left;
            padding: 0;
            background: rgba(0,0,0, 0.80);
            border-radius: 0px 0px 10px 10px;
            box-sizing: border-box;
            padding: 0px 10px 0px 0px;
            display: none;
            z-index: +999;
            border-bottom: rgba(247, 115, 0, 1.0) 2px solid;
            border-left: rgba(247, 115, 0, 1.0) 0px solid;
        }
        #SubMenu li {
            list-style: none;
            float: none;
            display: inline-table;
            width: 80%;
            margin-left: 10px;
            padding: 10px 10px;
            font-size: 16px;
            font-family: sans-serif;
            font-weight: 300;
            color: white;
        }
        .Fixedwidth {
            width: 100%;
            height: auto;
            overflow: auto;
            margin: 0 auto;
            background: rgba(0,0,0, 0.0);
            padding: 10px 0;
        }
        .Fixedwidth input {
            width: 150px;
            height: 31px;
        }
        #search {
            margin-left: 10px;
            margin-top: 5px;
            border: none;
            padding: 10px;
            box-sizing: border-box;
            border-radius:2px;
            box-shadow: inset rgba(0,0,0, 0.20) 1px 1px 5px 1px;
        }
        #submit {
            width: 80px;
            height: 31px;
            margin-left: 5px;
            border: none;
            padding: none;
            background: white;
            border-radius:2px;
        }
        .Content {
            width: 100%;
            height: auto;
            overflow: auto;
            text-align: center;
            float: left;
            z-index: -1;
            background: rgba(0,0,0,0.00);
            
        } 
        .Fixedwidthcontent {
            width: 100%;
            height: auto;
            overflow: auto;
            margin:  0 auto;
            background: rgba(255,255,255, 0.0);
            padding: 10px 20px;
            box-sizing: border-box;
            background-size: cover;
            background-position: 0px -100px;
            opacity: .3;
            z-index: -1;
            position: absolute;
            top: 56px;
            
        }  
        header h2 {
            width: 200px;
            font-family: sans-serif;
            float: left;
            margin: 0;
            color: aliceblue;
            font-weight: 400;
            padding-top: 3px;
            margin-left: 20px;
        }
        .cta-Container {
            width: 90%;
            height: auto;
            overflow: auto;
            background:rgba(0,0,0,0.05);
            border-radius: 20px;
            z-index: +999;
            margin: 0 auto;
            margin-top: 50px;
            font-family: sans-serif;
            color: black;
        }
        .cta-Container label {
            width: 100%;
            font-size: 22px;
            float: left;
            margin-bottom: 10px;
            margin-top: 10px;
        }
        
        .cta-Container  h1, label, h3 {
            color: rgba(0,0,0, 0.60);
        }
        .cta-Container input {
            float: left;
            width: 60%;
            margin-left: 20%;
            height: 30px;
            font-size: 14px;
            box-sizing: border-box;
            padding: 5px 10px;
        }
        .cta-Container textarea {
            width: 80%;
            height: 200px;
            margin-left: 10%;
            float: left;
            font-weight: 100;
            font-size: 14px;
            box-sizing: border-box;
            padding: 5px 10px;
        }
        #JoinNow {
            width: 15%;
            height: 35px;
            border: none;
            padding: none;
            background: rgba(0,0,0,0.05);
            float: left;
            border-radius:2px;
            font-size: 1em;
            margin-left: 42.5%;
            margin-top:20px;
            margin-bottom: 20px;
        }
        .Title {
            width: 100%;
            height: auto;
        }
        .Description {
            width: 100%;
            height: auto;
        }
        #signIn {
            float: right;
        }
    </style>
    <script>
     $(document).ready(function(){
         $('#Ac').click(function(){
            $('#Ac').toggleClass('AcHover')
            $('#SubMenu').slideDown(400); 
         });
         $('.Content').click(function(){
            $('#Ac').toggleClass('AcHover')
            $('#SubMenu').slideUp(400); 
         });
     });
    </script>
<body>
<div class="Container">
    <header>
    <div class="Fixedwidth"> 
        <h2><%= link_to 'The Alpha Blog', root_path %></h2>
        <ul> 
            <li>Articles</li>
            <li>Link</li>
            <li class="Active" id="Ac">Actions <strong>&#x25BC;</strong>
                <ul id="SubMenu">
                    <li><%= link_to 'New Article', new_path %></li>
                    <li>Popular Articles</li>
                    <li>Newsletters</li>
                    <hr>
                    <li>Separated Link</li>
                    <hr>
                    <li>Another Link</li>
                </ul>
            </li>
        </ul>
        <ul id="signIn">
            <li>Sign In</li>
            <li>Sign Up</li>
        </ul>
        <input type="text" placeholder="Search" name="search" id="search">
        <button type="submit" value="Submit" id="submit">Submit</button>
    </div>
    </header>
    <div class="Content"> 
        <div class="cta-Container">
            <h1>The Alpha Blog</h1>
            <h3><%= flash[:notice] %></h3>
            <div class="Title"><p>Title: <%= @article.title %></p></div>
            <div class="Description"> <p>Description: <%= @article.description %></p></div>
            
            
            <%= link_to "Edit", edit_article_path(@article) %> | <%= link_to "Back to article listings", articles_path %>
        </div>
        
        <div class="Fixedwidthcontent"> </div>
        
    </div>
    <footer>
        <small>All rights reserved @Alpha-Block: Display purposes for Jamell Daniels Portfolio</small>
    </footer>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <ul>
      <li>
        <li><%= msg %></li>
      </li>
    </ul>
  <% end %>
<%= yield %>

</body>
</html>